/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: UYn/BU6r3dRWZRSyaiZcDbrJsT9zIUt+nOz6rRkhZDHucaG+V0x9ERAxiSfDS4xlMnM50tE/IKdOqNSZDXDTWg==
 */

/* eslint-disable */
// tslint:disable

import {Roles} from './_enums'

interface User {
  /**
   * @default now()
   */
  created_at: (Date) | null
  /**
   * @default 2100
   */
  daily_calories_threshold: (number) | null
  email: string
  /**
   * @default nextval('user_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'user_id'}
  /**
   * @default true
   */
  isActive: (boolean) | null
  /**
   * @default 1000
   */
  monthly_expenses_threshold: (number) | null
  name: string
  password: string
  role: (Roles) | null
  updated_at: (Date) | null
}
export default User;

interface User_InsertParameters {
  /**
   * @default now()
   */
  created_at?: (Date) | null
  /**
   * @default 2100
   */
  daily_calories_threshold?: (number) | null
  email: string
  /**
   * @default nextval('user_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'user_id'}
  /**
   * @default true
   */
  isActive?: (boolean) | null
  /**
   * @default 1000
   */
  monthly_expenses_threshold?: (number) | null
  name: string
  password: string
  role?: (Roles) | null
  updated_at?: (Date) | null
}
export type {User_InsertParameters}
