/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: BbHP2LevlrzcP0nRNjutrMejKbdNDXK3SjOV1Fg2CalvXPCd1l2kbWynBkhtoFNldtgfEMYnWASQUg6f0G5M9A==
 */

/* eslint-disable */
// tslint:disable

type Roles = 'admin' | 'user';
export type {Roles}
