/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Qak9Dh0nBzyn6DyWq3wdZdvrxf+urb4HPaAu34XPvkU/ri3IqgQvbwwfZazN5UTh3v7LCsIrRbpOFcd7781HGQ==
 */

/* eslint-disable */
// tslint:disable

import Food, {Food_InsertParameters} from './food'
import Pgmigrations, {Pgmigrations_InsertParameters} from './pgmigrations'
import User, {User_InsertParameters} from './user'

interface DatabaseSchema {
  food: {record: Food, insert: Food_InsertParameters};
  pgmigrations: {record: Pgmigrations, insert: Pgmigrations_InsertParameters};
  user: {record: User, insert: User_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  User,
  User_InsertParameters,
  Food,
  Food_InsertParameters,
  Pgmigrations,
  Pgmigrations_InsertParameters,
}
